version: '3.3'
services:
    api:
        build: .
        image: cornatul/nlp:v1
        deploy:
          replicas: 5
        ports:
            - 8000:8000
        volumes:
            - type: bind
              source: .
              target: /app/
