version: '3.8'
services:
    api:
        build: .
        image: unixdevil/nlp:v1
        ports:
            - 8000:8000
        volumes:
            - type: bind
              source: .
              target: /app/
